# Generated by Django 5.2 on 2025-04-26 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_buy_signals', models.BooleanField(default=True)),
                ('notify_on_sell_signals', models.BooleanField(default=True)),
                ('min_score_for_buy_notification', models.IntegerField(default=75)),
                ('max_score_for_sell_notification', models.IntegerField(default=25)),
                ('preferred_indicators', models.JSONField(default=dict)),
                ('custom_weights', models.JSONField(default=dict)),
                ('risk_profile', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
