# Generated by Django 5.2 on 2025-04-26 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='custom_weights',
        ),
    ]
