# Generated by Django 5.2 on 2025-04-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0003_remove_userprofile_custom_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='market_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
