# Generated by Django 5.2 on 2025-04-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0004_analysisresult_market_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='market_date',
        ),
    ]
