# Generated by Django 5.2 on 2025-04-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0005_remove_analysisresult_market_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='market_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
