# Generated by Django 5.2 on 2025-04-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0007_remove_analysisresult_market_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_return', models.FloatField(help_text='Vorhergesagte prozentuale Veränderung')),
                ('predicted_price', models.FloatField(help_text='Vorhergesagter Preis')),
                ('recommendation', models.CharField(help_text='BUY, SELL, HOLD', max_length=10)),
                ('confidence', models.FloatField(default=0.0, help_text='Konfidenz der ML-Vorhersage (0-1)')),
                ('prediction_days', models.IntegerField(default=5, help_text='Anzahl der Tage für die Vorhersage')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='stock_analyzer.stock')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
