# Generated by Django 5.2 on 2025-04-28 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0008_mlprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('accuracy', models.FloatField(help_text='Genauigkeit des Klassifikationsmodells (0-1)')),
                ('rmse', models.FloatField(help_text='RMSE des Regressionsmodells')),
                ('feature_importance', models.JSONField(blank=True, help_text='Feature Importance als JSON', null=True)),
                ('confusion_matrix', models.JSONField(blank=True, help_text='Confusion Matrix als JSON', null=True)),
                ('directional_accuracy', models.FloatField(blank=True, help_text='Genauigkeit der Richtungsvorhersage (0-1)', null=True)),
                ('model_version', models.CharField(default='v1', help_text='Version des Modells', max_length=50)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_metrics', to='stock_analyzer.stock')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock', 'date', 'model_version')},
            },
        ),
    ]
